# Change these first
owner: nobody12021 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: AngelWorks Studios Website
    url: https://angelworksstudios.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.angelworksstudios.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AngelWorks Studios Status
  introTitle: "AngelWorks Studios Status"
  introMessage: This is the Status Page of all Websites and Servers owned by AngelWorks Studios. This Status Site is broken in the Moment. Yes ive managed to break the Site telling me when other Sites are broken. Dont ask how.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/nobody12021/status
workflowSchedule:
  uptime: "*/5 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
